# Surrey-Deployment.yaml
# kubectl apply -f <file name>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrey-deployment
  labels:
    app: surrey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surrey
  template:
    metadata:
      labels:
        app: surrey
    spec:
      containers:
        - name: surrey
          image: mutluokuducu/surrey:0.2
          ports:
            - containerPort: 8080

