# Surrey-Service.yaml
# kubectl apply -f <file name>
apiVersion: v1
kind: Service
metadata:
  name: surrey-service
spec:
  selector:
    app: surrey
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001